### ISSUE TITLE
Health / armor numbers

### ISSUE THREAD

**Issue by takesnodamage** [jekyllgrim/UniversalFlexibleHUD#10]
I tried to post this to the ZDoom forum thread but it's giving me some captcha php error...

The new version is really nice, I like the change you made to indicate the Berserk powerup and making it an overlay that can combo with a wad's custom HUD is really slick. Stuff like showing an overlay of the entire possible area the keys can take up so you don't have to guess where they might overlap something was thoughtful as well.

One of the very few things that still trips me up sometimes, with green armor the numbers for health and armor are the same font/color so it can be hard to glance down in the middle of a fight and quickly tell which is which. Is there a way to change the color of health, or move them independently of one another to space things out? If the color is hardcoded, maybe something like making health red, then armor could be green for regular and blue for megaarmor?

**Comment by jekyllgrim** [comment]
I can add options to colors, so that, for example, the color can be fixed,
or a range (blue-green-orange-yellow-red). I could also probably add an
option to let the user choose between "numbers" and "bars" modes for HP and
armor independently.

чт, 22 февр. 2024 г. в 08:15, takesnodamage ***@***.***>:

**Comment by takesnodamage** [comment]
Awesome, being able to pick a unique color for health or have one be a number and one be a bar (that could also hopefully cycle through the same color options) should make them more readable at a glance.

**Comment by jekyllgrim** [comment]
Customizable color options and color ranges added in 909d44e1d010ef655f2d7d96fd42e871e3679103
