### ISSUE TITLE
Armor absorption indicator?

### ISSUE THREAD

**Issue by Solstice2335** [jekyllgrim/UniversalFlexibleHUD#11]
Would it be possible to add an option to replace the armor type indicator by the armor meter with the percent of damage your armor absorbs? Like instead of a green armor sprite, it would actually display the number 33 or something to that effect. It might seem silly but with the vast variety of mods that add or remove armor types or don't even use sprites for armor pickups, it would be nice to know exactly how much protection I really have.

Apparently GitHub lets you attach files in issue requests so I've attached a 'mod' I already use (literally just a zscript.txt file inside a .zip) that might help if you need it. It appears to be an eventhandler just like the new version of the HUD. [armour_print.zip](https://github.com/jekyllgrim/UniversalFlexibleHUD/files/14395909/armour_print.zip)

Also, sorry if this isn't really an 'issue.' I wasn't sure how else to ask this question besides posting on the ZDoom forums and the account creation process for that seems to dislike me.

**Comment by jekyllgrim** [comment]
Valid idea. I'll look into this.

**Comment by jekyllgrim** [comment]
Added in 96571a66c8bd79017505431044cd4af18d130e14 (with the relevant LANGUAGE strings added in 35b9b301c4c9b15482220470cd93c94f5da9674d)
You will now have an "Armor icon/absorption display" option under "Health and Armor display" menu, where you can switch between display an icon, absorption percentage, or both (icon with percentage on top).
You can [download the current build](https://github.com/jekyllgrim/UniversalFlexibleHUD/archive/refs/heads/main.zip) or wait until the next release. Thanks for the suggestion :)
