### ISSUE TITLE
[BUG] Minimap does not respect Map Marker status (enabled/disabled), and shows everything anyway.

### ISSUE THREAD

**Issue by SinaelDOverom** [jekyllgrim/UniversalFlexibleHUD#17]
Currently Minimap does not respect Map Marker enabled/disabled propery and shows all map markers as if they were enabled, even if they are not.
![Screenshot_Doom_20240422_145227](https://github.com/jekyllgrim/UniversalFlexibleHUD/assets/61930430/05765e56-7ae6-4d60-be39-7174e481f814)
![Screenshot_Doom_20240422_145223](https://github.com/jekyllgrim/UniversalFlexibleHUD/assets/61930430/5ae4060e-3094-49f9-b396-a7c30ee6a2d4)

**Comment by SinaelDOverom** [comment]
> Is this about the marker settings in GZDoom itself, not in FlexiHUD settings?

It is Flexi Hud, notice in the minimap there are map markers for items that are not there on the main map

If the map marker is stated as disabled (like objective that is not yet revealed in SUPPLICE), minimap will still show it.

**Comment by jekyllgrim** [comment]
Should be fixed in 510cbdd2ef8c0f58c8c23695c84aec1e5d5d8157
