### ISSUE TITLE
[BUG?] Ammo counter highlights first ammo type even if it's not the ammo type used by the gun.

### ISSUE THREAD

**Issue by SinaelDOverom** [jekyllgrim/UniversalFlexibleHUD#18]
IDK how it's supposed to work, but currently ammo counter highlights first ammo type even if it's not the ammo type used by the gun.
Maybe a bug, may be not, but IMO it should highlight the ammo the gun is using.

**Comment by jekyllgrim** [comment]
Seems to be a new bug after a GZDoom update, will be investigating.

**Comment by jekyllgrim** [comment]
Fixed in 6f1b43ad60dd55a18407770dfec662e1cc119af2
