### ISSUE TITLE
Failure when saving game

### ISSUE THREAD

**Issue by NonEmployee** [jekyllgrim/UniversalFlexibleHUD#2]
This was mentioned on ZDoom Forums, but I wanted to add a screenshot. Unlike the previous time saving didn't work, this doesn't require an enemy to be killed before it stops working. 

![save crash](https://github.com/jekyllgrim/UniversalFlexibleHUD/assets/149312540/1d8d9f8d-928d-4ded-8019-8bccc6634868)

**Comment by TwelveEyes** [comment]
https://github.com/jekyllgrim/UniversalFlexibleHUD/blob/1c604e089705b3fb15c3de54eafec57e1e56db01/UFHZScript/ufh_dataclasses.zs#L103-L104

setting these variables as `transient` should fix it

**Comment by NonEmployee** [comment]
Ah so it's a problem with the damage markers change. I thought it may have been a problem before that update, but I guess not.

**Comment by jekyllgrim** [comment]
Thanks, fixed in 789f7f879638f7e479b00eeada8b8dc7c9064804
