### ISSUE TITLE
[Enhancement] Disable while on titlemap

### ISSUE THREAD

**Issue by IrisWasTaken1** [jekyllgrim/UniversalFlexibleHUD#23]
A check should be added that detects whether the name of the map is TITLEMAP, if comes back as true, than don't render anything.

What currently happens:
![image](https://github.com/jekyllgrim/UniversalFlexibleHUD/assets/93811191/0a1a6207-1ac6-46e9-91e6-3cffbe989c56)
What should happen:
![image](https://github.com/jekyllgrim/UniversalFlexibleHUD/assets/93811191/db0ebac7-1f96-4e32-b340-ddbd47d82611)

**Comment by jekyllgrim** [comment]
Can't believe I made this oversight, lol. Anyway, fixed in a781f18149f0c8e81493b8ecd6189ca77c8a0a6e
