### ISSUE TITLE
[FEATURE REQUEST] Separate the armor and health elements from the mugshot.

### ISSUE THREAD

**Issue by Sol1vaN** [jekyllgrim/UniversalFlexibleHUD#26]
That's it, I want to manage the mugshot on my way.
Many mods already have his own armor/healt element, like DOOM PCX CE
But DOOM PCX CE don't have mugshot, so there's the conflict.
The other problem is I want to put the armor/healt on different places, but all this elements (armor, healt and armor) are linked.
Some times, depending of the mod, I don't want to use the armor/healt from UFHUD.
On this case, I only want to use the mugshot to put it on DOOM PCX CE.

So, is possible to implement this?

**Comment by jekyllgrim** [comment]
It's already an option in the dev build https://github.com/jekyllgrim/UniversalFlexibleHUD/archive/refs/heads/main.zip
FlexiHUD settings > Mugshot > Independent

**Comment by Sol1vaN** [comment]
i've tested, and this is perfect now.
thanks very much!!!
