### ISSUE TITLE
Some scaling options and others (pull request)

### ISSUE THREAD

**Issue by Sol1vaN** [jekyllgrim/UniversalFlexibleHUD#9]
Hi there.

Your mod is incredible, but it need some little changes/additions to be perfect.
Bring to this mod the cool options from Fullscreen Statusbar Mod:
https://github.com/3saster/fullscrn_huds
i mean:
- possibility to turn off status bar on map mode
- possibility to chose a different color for completions stats (when you found all secrets, the font color can be changed by user chose)

now, there's new somethings that this mod needs:
- separate scaling for stats :kills, items, secrets (because minimap scale have too much difference between stats and minimap objet)
- separate scaling for current ammo and weapon section
- separate scaling for keys
- possitiblity to change the color of stats font
- possitiblity to change the color of stats font

finally, there's some request that would be nice to implement:
-making compatible with Precise Crosshair (the healt/armor/ammo hud bars around the crosshair, follow the movement point to where you actually shoot* instead of the center of the screen).
https://github.com/mmaulwurff/precise-crosshair

I hope you can read this 😌

**Comment by jekyllgrim** [comment]
Good news about Precise Crosshair: turns out, m8f is wise and exposed the position of his crosshair to a CVar. So I will indeed add compatibility with it :)

**Comment by jekyllgrim** [comment]
The [current build](https://github.com/jekyllgrim/UniversalFlexibleHUD/archive/refs/heads/main.zip) now will automatically adjust reticle bars to match Precise Crosshair if it's in the load order. There's also now a new menu, "Appearance options", where the scaling of each FlexiHUD element can be changed individually.

**Comment by jekyllgrim** [comment]
Per-element scaling added in 7958ec6178018a9884499cb42097b583e4c94d26
Custom fonts added in e94525b7d922877cb831dfbb5f1350cbfaaa484d

**Comment by Sol1vaN** [comment]
ill probe right now.
i'm exited.

**Comment by sanscriptum** [comment]
Hi, mapstats lines (Kills, Items, Keys, Timer) still look very small next to the minimap and can't be scaled, please add them as well.

**Comment by Sol1vaN** [comment]
all work fine, i'm probe it a lot, and is perfect.
but, it need a little one thing: separate the armor and health elements from the mugshot.
because only want to see the mugshot on a specific point.
i'll create a new request for this.

**Comment by jekyllgrim** [comment]
> all work fine, i'm probe it a lot, and is perfect. but, it need a little one thing: separate the armor and health elements from the mugshot. because only want to see the mugshot on a specific point. i'll create a new request for this.

This is already an option in a dev build. FlexiHUD Settings > Mugshot > Mugshot Display Mode. Set it to Independent, and the mughsot will be a separate element.
